config/routes.rb
Rails.application.routes.draw do
  root "reservations#index"
  get "list", to: "reservations#list"

  resources :reservations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    validates :name, presence: true
    validates :phone, presence: true
    validates :instagram, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :create]

    def index
        @reservation = Reservation.new
    end

    def show
        @reservation = Reservation.find(params[:id])
    end

    def create
        @reservation = Reservation.new(reservation_params)
        if @reservation.save
            redirect_to index
        else
            render :index
        end
    end

    def destroy
        @reservation = Reservation.find(params[:id])
        @reservation.destroy

        redirect_to list_path
    end

    def list
        @reservations = Reservation.all
    end


    private
        def reservation_params
            params.require(:reservation).permit(:name, :phone, :instagram)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KEVIN'S CLASSICS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reservations/_form.html.erb
<%= form_with model: reservation, id: "order" do |form| %>
    <p id="signup">sign up to reserve your spot in line</p><br>
        <%= form.label :name, "name" %>
        <%= form.text_field :name, id: "name" %><br>
        <%= form.label :phone, "phone" %>
        <%= form.text_field :phone, id: "phone" %><br>
        <%= form.label :instagram, "instagram" %>
        <%= form.text_field :instagram, id: "instagram" %><br><br>   
        <%= form.submit "submit", id: 'submit' %><br><br>
    <p id=everybody>everybody eats&trade;</p><br>
<% end %>

app/views/reservations/index.html.erb
<!DOCTYPE HTML>
<html>
<head>
    <%= stylesheet_link_tag 'reservation' %>
    <link href="https://allfont.net/allfont.css?fonts=agency-fb-bold" rel="stylesheet" type="text/css" />
</head>
<body>
    <%= image_tag 'logo-transparent.png', id: 'logo' %>
    <br><br><br>

    <%= render "form", reservation: @reservation %>

    <br><br>
    <div id=pics> 
        <%= image_tag 'pizza-1.jpeg', id: 'left-pizza' %>
        <%= image_tag 'pizza-2.jpeg', id: 'right-pizza' %>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        <a href=https://www.instagram.com/aka_kcg>
        <%= image_tag 'instagram-logo.jpg', id: 'instagram-logo' %>
        </a>
        <br>
        <p id="follow">@aka_kcg</p>
    </div>
</body>
</html>

app/views/reservations/list.html.erb
<!DOCTYPE HTML>
<html>
<head>
</head>
<body>
<% @reservations.each do |reservation| %>
    <h3>Reservation <%= reservation.id %></h3>
    <li>
    <%= reservation.name %>
    </li>
    <li>
    <%= reservation.phone %>
    </li>
    <li>
    <%= reservation.instagram %>
    </li>
    <%= button_to "Delete", reservation_path(reservation), method: :delete  %>
<% end %>
</body>
</html>